Configure AWS

diff --git a/.github/workflows/app-ci.yml b/.github/workflows/app-ci.yml
--- a/.github/workflows/app-ci.yml
+++ b/.github/workflows/app-ci.yml
@@ -190,7 +190,7 @@ jobs:
       - name: Install Cosign
         uses: sigstore/cosign-installer@v3
 
-      # -------------------------
+           # -------------------------
       # Phase 14 - Configure AWS
       # -------------------------
 
@@ -214,12 +214,44 @@ jobs:
           tags: |
             ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
 
+      # -------------------------
+      # Debug GitHub OIDC Token
+      # -------------------------
+
+      - name: Check GitHub OIDC Token
+        run: |
+          echo "===== OIDC REQUEST URL ====="
+          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
+
+          echo ""
+          echo "===== OIDC REQUEST TOKEN ====="
+          if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
+            echo "Token exists ✅"
+          else
+            echo "Token missing ❌"
+            exit 1
+          fi
+
+          echo ""
+          echo "===== OIDC RESPONSE ====="
+          curl -s \
+            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sigstore"
+
+      # -------------------------
+      # Phase 15 - Sign Image
+      # -------------------------
+
       - name: Sign Docker Image
         env:
           COSIGN_EXPERIMENTAL: "1"
         run: |
           cosign sign --yes \
             ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
+
+      # -------------------------
+      # Phase 16 - Verify Signature
+      # -------------------------
 
       - name: Verify Docker Image Signature
         run: |
